version: '3.8'

services:
  factorial:
    image: factorial
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443"
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Passw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx

    volumes:
      - ~/.aspnet/https:/https/
